const fs = require('fs')
const path = require('path')

const TURKEY_PROVINCES = [
  'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin',
  'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa',
  'Çanakkale', 'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan',
  'Erzurum', 'Eskişehir', 'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta',
  'Mersin', 'İstanbul', 'İzmir', 'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir',
  'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla',
  'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya', 'Samsun', 'Siirt',
  'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak',
  'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman',
  'Şırnak', 'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce'
]

const TURKEY_DISTRICTS = [
  { city: 'Kadıköy', state: 'İstanbul' },
  { city: 'Beşiktaş', state: 'İstanbul' },
  { city: 'Üsküdar', state: 'İstanbul' },
  { city: 'Şişli', state: 'İstanbul' },
  { city: 'Bakırköy', state: 'İstanbul' },
  { city: 'Beyoğlu', state: 'İstanbul' },
  { city: 'Sarıyer', state: 'İstanbul' },
  { city: 'Fatih', state: 'İstanbul' },
  { city: 'Maltepe', state: 'İstanbul' },
  { city: 'Ataşehir', state: 'İstanbul' },
  { city: 'Pendik', state: 'İstanbul' },
  { city: 'Kartal', state: 'İstanbul' },
  { city: 'Beylikdüzü', state: 'İstanbul' },
  { city: 'Başakşehir', state: 'İstanbul' },
  { city: 'Çankaya', state: 'Ankara' },
  { city: 'Keçiören', state: 'Ankara' },
  { city: 'Yenimahalle', state: 'Ankara' },
  { city: 'Mamak', state: 'Ankara' },
  { city: 'Etimesgut', state: 'Ankara' },
  { city: 'Karşıyaka', state: 'İzmir' },
  { city: 'Konak', state: 'İzmir' },
  { city: 'Bornova', state: 'İzmir' },
  { city: 'Buca', state: 'İzmir' },
  { city: 'Çeşme', state: 'İzmir' },
  { city: 'Urla', state: 'İzmir' },
  { city: 'Muratpaşa', state: 'Antalya' },
  { city: 'Konyaaltı', state: 'Antalya' },
  { city: 'Kepez', state: 'Antalya' },
  { city: 'Alanya', state: 'Antalya' },
  { city: 'Manavgat', state: 'Antalya' },
  { city: 'Kemer', state: 'Antalya' },
  { city: 'Kaş', state: 'Antalya' },
  { city: 'Bodrum', state: 'Muğla' },
  { city: 'Fethiye', state: 'Muğla' },
  { city: 'Marmaris', state: 'Muğla' },
  { city: 'Datça', state: 'Muğla' },
  { city: 'Nilüfer', state: 'Bursa' },
  { city: 'Osmangazi', state: 'Bursa' },
  { city: 'Yıldırım', state: 'Bursa' },
  { city: 'Gebze', state: 'Kocaeli' },
  { city: 'İzmit', state: 'Kocaeli' },
  { city: 'Seyhan', state: 'Adana' },
  { city: 'Çukurova', state: 'Adana' },
  { city: 'Şahinbey', state: 'Gaziantep' },
  { city: 'Şehitkamil', state: 'Gaziantep' },
  { city: 'Melikgazi', state: 'Kayseri' },
  { city: 'Kocasinan', state: 'Kayseri' },
  { city: 'Odunpazarı', state: 'Eskişehir' },
  { city: 'Tepebaşı', state: 'Eskişehir' },
  { city: 'Selçuklu', state: 'Konya' },
  { city: 'Meram', state: 'Konya' },
  { city: 'Karatay', state: 'Konya' },
  { city: 'Ortahisar', state: 'Trabzon' },
  { city: 'Akçaabat', state: 'Trabzon' }
]

const WORLD_CITIES = [
  // Amerika Kıtası
  { city: 'New York', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: ['nyc', 'new york city', 'ny'] },
  { city: 'Los Angeles', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: ['la'] },
  { city: 'Chicago', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: ['sikago'] },
  { city: 'Houston', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: [] },
  { city: 'Miami', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: [] },
  { city: 'San Francisco', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: ['sf'] },
  { city: 'Washington, D.C.', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: ['washington', 'dc'] },
  { city: 'Boston', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: [] },
  { city: 'Seattle', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: [] },
  { city: 'Las Vegas', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: ['vegas'] },
  { city: 'Atlanta', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: [] },
  { city: 'Dallas', countryTr: 'Amerika Birleşik Devletleri', countryEn: 'United States', aliases: [] },
  { city: 'Toronto', countryTr: 'Kanada', countryEn: 'Canada', aliases: [] },
  { city: 'Vancouver', countryTr: 'Kanada', countryEn: 'Canada', aliases: [] },
  { city: 'Montreal', countryTr: 'Kanada', countryEn: 'Canada', aliases: [] },
  { city: 'Ottawa', countryTr: 'Kanada', countryEn: 'Canada', aliases: [] },
  { city: 'Mexico City', countryTr: 'Meksika', countryEn: 'Mexico', aliases: ['meksiko', 'ciudad de mexico'] },
  { city: 'Cancun', countryTr: 'Meksika', countryEn: 'Mexico', aliases: ['kankun'] },
  { city: 'Guadalajara', countryTr: 'Meksika', countryEn: 'Mexico', aliases: [] },
  { city: 'São Paulo', countryTr: 'Brezilya', countryEn: 'Brazil', aliases: ['sao paulo'] },
  { city: 'Rio de Janeiro', countryTr: 'Brezilya', countryEn: 'Brazil', aliases: ['rio'] },
  { city: 'Brasília', countryTr: 'Brezilya', countryEn: 'Brazil', aliases: ['brasilia'] },
  { city: 'Buenos Aires', countryTr: 'Arjantin', countryEn: 'Argentina', aliases: [] },
  { city: 'Santiago', countryTr: 'Şili', countryEn: 'Chile', aliases: ['sili'] },
  { city: 'Bogota', countryTr: 'Kolombiya', countryEn: 'Colombia', aliases: [] },
  { city: 'Medellin', countryTr: 'Kolombiya', countryEn: 'Colombia', aliases: [] },
  { city: 'Lima', countryTr: 'Peru', countryEn: 'Peru', aliases: [] },
  { city: 'Havana', countryTr: 'Küba', countryEn: 'Cuba', aliases: ['kuba'] },

  // Avrupa
  { city: 'Londra', countryTr: 'Birleşik Krallık', countryEn: 'United Kingdom', aliases: ['london', 'ingiltere', 'uk'] },
  { city: 'Manchester', countryTr: 'Birleşik Krallık', countryEn: 'United Kingdom', aliases: [] },
  { city: 'Birmingham', countryTr: 'Birleşik Krallık', countryEn: 'United Kingdom', aliases: [] },
  { city: 'Liverpool', countryTr: 'Birleşik Krallık', countryEn: 'United Kingdom', aliases: [] },
  { city: 'Edinburgh', countryTr: 'Birleşik Krallık', countryEn: 'United Kingdom', aliases: ['edinburg', 'iskocya'] },
  { city: 'Glasgow', countryTr: 'Birleşik Krallık', countryEn: 'United Kingdom', aliases: [] },
  { city: 'Dublin', countryTr: 'İrlanda', countryEn: 'Ireland', aliases: ['irlanda'] },
  { city: 'Paris', countryTr: 'Fransa', countryEn: 'France', aliases: ['fransa'] },
  { city: 'Marsilya', countryTr: 'Fransa', countryEn: 'France', aliases: ['marseille'] },
  { city: 'Lyon', countryTr: 'Fransa', countryEn: 'France', aliases: [] },
  { city: 'Nice', countryTr: 'Fransa', countryEn: 'France', aliases: ['nis'] },
  { city: 'Toulouse', countryTr: 'Fransa', countryEn: 'France', aliases: [] },
  { city: 'Strazburg', countryTr: 'Fransa', countryEn: 'France', aliases: ['strasbourg'] },
  { city: 'Berlin', countryTr: 'Almanya', countryEn: 'Germany', aliases: ['almanya', 'deutschland'] },
  { city: 'Münih', countryTr: 'Almanya', countryEn: 'Germany', aliases: ['munich', 'münchen', 'munchen'] },
  { city: 'Frankfurt', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Hamburg', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Köln', countryTr: 'Almanya', countryEn: 'Germany', aliases: ['cologne', 'koln'] },
  { city: 'Stuttgart', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Düsseldorf', countryTr: 'Almanya', countryEn: 'Germany', aliases: ['dusseldorf'] },
  { city: 'Dortmund', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Leipzig', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Bremen', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Dresden', countryTr: 'Almanya', countryEn: 'Germany', aliases: [] },
  { city: 'Nürnberg', countryTr: 'Almanya', countryEn: 'Germany', aliases: ['nuremberg', 'nurnberg'] },
  { city: 'Hannover', countryTr: 'Almanya', countryEn: 'Germany', aliases: ['hanover'] },
  { city: 'Roma', countryTr: 'İtalya', countryEn: 'Italy', aliases: ['rome', 'italya', 'italia'] },
  { city: 'Milano', countryTr: 'İtalya', countryEn: 'Italy', aliases: ['milan'] },
  { city: 'Napoli', countryTr: 'İtalya', countryEn: 'Italy', aliases: ['naples'] },
  { city: 'Torino', countryTr: 'İtalya', countryEn: 'Italy', aliases: ['turin'] },
  { city: 'Floransa', countryTr: 'İtalya', countryEn: 'Italy', aliases: ['florence', 'firenze'] },
  { city: 'Venedik', countryTr: 'İtalya', countryEn: 'Italy', aliases: ['venice', 'venezia'] },
  { city: 'Bologna', countryTr: 'İtalya', countryEn: 'Italy', aliases: [] },
  { city: 'Madrid', countryTr: 'İspanya', countryEn: 'Spain', aliases: ['ispanya', 'espana'] },
  { city: 'Barselona', countryTr: 'İspanya', countryEn: 'Spain', aliases: ['barcelona'] },
  { city: 'Valensiya', countryTr: 'İspanya', countryEn: 'Spain', aliases: ['valencia'] },
  { city: 'Sevilla', countryTr: 'İspanya', countryEn: 'Spain', aliases: ['seville'] },
  { city: 'Malaga', countryTr: 'İspanya', countryEn: 'Spain', aliases: [] },
  { city: 'Bilbao', countryTr: 'İspanya', countryEn: 'Spain', aliases: [] },
  { city: 'Lizbon', countryTr: 'Portekiz', countryEn: 'Portugal', aliases: ['lisbon', 'lisboa', 'portekiz'] },
  { city: 'Porto', countryTr: 'Portekiz', countryEn: 'Portugal', aliases: [] },
  { city: 'Amsterdam', countryTr: 'Hollanda', countryEn: 'Netherlands', aliases: ['hollanda'] },
  { city: 'Rotterdam', countryTr: 'Hollanda', countryEn: 'Netherlands', aliases: [] },
  { city: 'Lahey', countryTr: 'Hollanda', countryEn: 'Netherlands', aliases: ['the hague', 'den haag'] },
  { city: 'Utrecht', countryTr: 'Hollanda', countryEn: 'Netherlands', aliases: [] },
  { city: 'Eindhoven', countryTr: 'Hollanda', countryEn: 'Netherlands', aliases: [] },
  { city: 'Brüksel', countryTr: 'Belçika', countryEn: 'Belgium', aliases: ['brussels', 'bruxelles', 'belcika'] },
  { city: 'Antwerp', countryTr: 'Belçika', countryEn: 'Belgium', aliases: ['anvers'] },
  { city: 'Gent', countryTr: 'Belçika', countryEn: 'Belgium', aliases: ['ghent'] },
  { city: 'Brugge', countryTr: 'Belçika', countryEn: 'Belgium', aliases: ['bruges'] },
  { city: 'Viyana', countryTr: 'Avusturya', countryEn: 'Austria', aliases: ['vienna', 'wien', 'avusturya'] },
  { city: 'Salzburg', countryTr: 'Avusturya', countryEn: 'Austria', aliases: [] },
  { city: 'Innsbruck', countryTr: 'Avusturya', countryEn: 'Austria', aliases: [] },
  { city: 'Graz', countryTr: 'Avusturya', countryEn: 'Austria', aliases: [] },
  { city: 'Zürih', countryTr: 'İsviçre', countryEn: 'Switzerland', aliases: ['zurich', 'isvicre'] },
  { city: 'Cenevre', countryTr: 'İsviçre', countryEn: 'Switzerland', aliases: ['geneva', 'geneve'] },
  { city: 'Basel', countryTr: 'İsviçre', countryEn: 'Switzerland', aliases: [] },
  { city: 'Bern', countryTr: 'İsviçre', countryEn: 'Switzerland', aliases: [] },
  { city: 'Lozan', countryTr: 'İsviçre', countryEn: 'Switzerland', aliases: ['lausanne'] },
  { city: 'Prag', countryTr: 'Çekya', countryEn: 'Czech Republic', aliases: ['prague', 'praha', 'cekya'] },
  { city: 'Brno', countryTr: 'Çekya', countryEn: 'Czech Republic', aliases: [] },
  { city: 'Varşova', countryTr: 'Polonya', countryEn: 'Poland', aliases: ['warsaw', 'warszawa', 'polonya'] },
  { city: 'Krakow', countryTr: 'Polonya', countryEn: 'Poland', aliases: [] },
  { city: 'Wroclaw', countryTr: 'Polonya', countryEn: 'Poland', aliases: [] },
  { city: 'Gdansk', countryTr: 'Polonya', countryEn: 'Poland', aliases: [] },
  { city: 'Budapeşte', countryTr: 'Macaristan', countryEn: 'Hungary', aliases: ['budapest', 'macaristan'] },
  { city: 'Kopenhag', countryTr: 'Danimarka', countryEn: 'Denmark', aliases: ['copenhagen', 'kobenhavn', 'danimarka'] },
  { city: 'Aarhus', countryTr: 'Danimarka', countryEn: 'Denmark', aliases: [] },
  { city: 'Stockholm', countryTr: 'İsveç', countryEn: 'Sweden', aliases: ['isvec'] },
  { city: 'Göteborg', countryTr: 'İsveç', countryEn: 'Sweden', aliases: ['gothenburg', 'goteborg'] },
  { city: 'Malmö', countryTr: 'İsveç', countryEn: 'Sweden', aliases: ['malmo'] },
  { city: 'Oslo', countryTr: 'Norveç', countryEn: 'Norway', aliases: ['norvec'] },
  { city: 'Bergen', countryTr: 'Norveç', countryEn: 'Norway', aliases: [] },
  { city: 'Helsinki', countryTr: 'Finlandiya', countryEn: 'Finland', aliases: ['finlandiya'] },
  { city: 'Espoo', countryTr: 'Finlandiya', countryEn: 'Finland', aliases: [] },
  { city: 'Tampere', countryTr: 'Finlandiya', countryEn: 'Finland', aliases: [] },
  { city: 'Atina', countryTr: 'Yunanistan', countryEn: 'Greece', aliases: ['athens', 'athina', 'yunanistan'] },
  { city: 'Selanik', countryTr: 'Yunanistan', countryEn: 'Greece', aliases: ['thessaloniki', 'salonika'] },
  { city: 'Girit', countryTr: 'Yunanistan', countryEn: 'Greece', aliases: ['crete', 'heraklion'] },
  { city: 'Rodos', countryTr: 'Yunanistan', countryEn: 'Greece', aliases: ['rhodes'] },
  { city: 'Bükreş', countryTr: 'Romanya', countryEn: 'Romania', aliases: ['bucharest', 'bucuresti', 'romanya'] },
  { city: 'Kaloşvar', countryTr: 'Romanya', countryEn: 'Romania', aliases: ['cluj-napoca'] },
  { city: 'Sofya', countryTr: 'Bulgaristan', countryEn: 'Bulgaria', aliases: ['sofia', 'bulgaristan'] },
  { city: 'Filibe', countryTr: 'Bulgaristan', countryEn: 'Bulgaria', aliases: ['plovdiv'] },
  { city: 'Varna', countryTr: 'Bulgaristan', countryEn: 'Bulgaria', aliases: [] },
  { city: 'Belgrad', countryTr: 'Sırbistan', countryEn: 'Serbia', aliases: ['belgrade', 'beograd', 'sirbistan'] },
  { city: 'Novi Sad', countryTr: 'Sırbistan', countryEn: 'Serbia', aliases: [] },
  { city: 'Zagreb', countryTr: 'Hırvatistan', countryEn: 'Croatia', aliases: ['hirvatistan'] },
  { city: 'Split', countryTr: 'Hırvatistan', countryEn: 'Croatia', aliases: [] },
  { city: 'Dubrovnik', countryTr: 'Hırvatistan', countryEn: 'Croatia', aliases: [] },
  { city: 'Saraybosna', countryTr: 'Bosna-Hersek', countryEn: 'Bosnia and Herzegovina', aliases: ['sarajevo', 'bosna'] },
  { city: 'Mostar', countryTr: 'Bosna-Hersek', countryEn: 'Bosnia and Herzegovina', aliases: [] },
  { city: 'Üsküp', countryTr: 'Kuzey Makedonya', countryEn: 'North Macedonia', aliases: ['skopje', 'makedonya'] },
  { city: 'Ohrid', countryTr: 'Kuzey Makedonya', countryEn: 'North Macedonia', aliases: [] },
  { city: 'Tiran', countryTr: 'Arnavutluk', countryEn: 'Albania', aliases: ['tirana', 'arnavutluk'] },
  { city: 'Podgorica', countryTr: 'Karadağ', countryEn: 'Montenegro', aliases: ['karadag'] },
  { city: 'Kotor', countryTr: 'Karadağ', countryEn: 'Montenegro', aliases: [] },
  { city: 'Priştine', countryTr: 'Kosova', countryEn: 'Kosovo', aliases: ['pristina', 'kosova'] },
  { city: 'Prizren', countryTr: 'Kosova', countryEn: 'Kosovo', aliases: [] },
  { city: 'Lefkoşa', countryTr: 'Kuzey Kıbrıs', countryEn: 'Northern Cyprus', aliases: ['nicosia', 'kibris', 'kktc'] },
  { city: 'Girne', countryTr: 'Kuzey Kıbrıs', countryEn: 'Northern Cyprus', aliases: ['kyrenia'] },
  { city: 'Gazimağusa', countryTr: 'Kuzey Kıbrıs', countryEn: 'Northern Cyprus', aliases: ['famagusta'] },
  { city: 'Limasol', countryTr: 'Kıbrıs', countryEn: 'Cyprus', aliases: ['limassol'] },
  { city: 'Larnaka', countryTr: 'Kıbrıs', countryEn: 'Larnaca', aliases: [] },
  { city: 'Valletta', countryTr: 'Malta', countryEn: 'Malta', aliases: [] },
  { city: 'Reykjavik', countryTr: 'İzlanda', countryEn: 'Iceland', aliases: ['izlanda'] },
  { city: 'Lüksemburg', countryTr: 'Lüksemburg', countryEn: 'Luxembourg', aliases: ['luxembourg', 'luksemburg'] },
  { city: 'Tallinn', countryTr: 'Estonya', countryEn: 'Estonia', aliases: ['estonya'] },
  { city: 'Riga', countryTr: 'Letonya', countryEn: 'Latvia', aliases: ['letonya'] },
  { city: 'Vilnius', countryTr: 'Litvanya', countryEn: 'Lithuania', aliases: ['litvanya'] },
  { city: 'Kiev', countryTr: 'Ukrayna', countryEn: 'Ukraine', aliases: ['kyiv', 'ukrayna'] },
  { city: 'Lviv', countryTr: 'Ukrayna', countryEn: 'Ukraine', aliases: [] },
  { city: 'Odessa', countryTr: 'Ukrayna', countryEn: 'Ukraine', aliases: [] },
  { city: 'Harkov', countryTr: 'Ukrayna', countryEn: 'Ukraine', aliases: ['kharkiv'] },
  { city: 'Minsk', countryTr: 'Belarus', countryEn: 'Belarus', aliases: ['beyaz rusya'] },
  { city: 'Kişinev', countryTr: 'Moldova', countryEn: 'Moldova', aliases: ['chisinau'] },
  { city: 'Moskova', countryTr: 'Rusya', countryEn: 'Russia', aliases: ['moscow', 'moskva', 'rusya'] },
  { city: 'St. Petersburg', countryTr: 'Rusya', countryEn: 'Russia', aliases: ['saint petersburg', 'leningrad'] },
  { city: 'Kazan', countryTr: 'Rusya', countryEn: 'Russia', aliases: [] },
  { city: 'Soçi', countryTr: 'Rusya', countryEn: 'Russia', aliases: ['sochi'] },
  { city: 'Novosibirsk', countryTr: 'Rusya', countryEn: 'Russia', aliases: [] },

  // Asya & Kafkaslar & Orta Doğu
  { city: 'Bakü', countryTr: 'Azerbaycan', countryEn: 'Azerbaijan', aliases: ['baku', 'azerbaycan'] },
  { city: 'Gence', countryTr: 'Azerbaycan', countryEn: 'Azerbaijan', aliases: ['ganja'] },
  { city: 'Sumgayıt', countryTr: 'Azerbaycan', countryEn: 'Azerbaijan', aliases: ['sumqayit'] },
  { city: 'Tiflis', countryTr: 'Gürcistan', countryEn: 'Georgia', aliases: ['tbilisi', 'gurcistan'] },
  { city: 'Batum', countryTr: 'Gürcistan', countryEn: 'Georgia', aliases: ['batumi'] },
  { city: 'Erivan', countryTr: 'Ermenistan', countryEn: 'Armenia', aliases: ['yerevan', 'ermenistan'] },
  { city: 'Astana', countryTr: 'Kazakistan', countryEn: 'Kazakhstan', aliases: ['nur-sultan', 'kazakistan'] },
  { city: 'Almatı', countryTr: 'Kazakistan', countryEn: 'Kazakhstan', aliases: ['almaty'] },
  { city: 'Şımkent', countryTr: 'Kazakistan', countryEn: 'Kazakhstan', aliases: ['shymkent'] },
  { city: 'Taşkent', countryTr: 'Özbekistan', countryEn: 'Uzbekistan', aliases: ['tashkent', 'ozbekistan'] },
  { city: 'Semerkant', countryTr: 'Özbekistan', countryEn: 'Uzbekistan', aliases: ['samarkand'] },
  { city: 'Buhara', countryTr: 'Özbekistan', countryEn: 'Uzbekistan', aliases: ['bukhara'] },
  { city: 'Aşkabat', countryTr: 'Türkmenistan', countryEn: 'Turkmenistan', aliases: ['ashgabat', 'turkmenistan'] },
  { city: 'Bişkek', countryTr: 'Kırgızistan', countryEn: 'Kyrgyzstan', aliases: ['bishkek', 'kirgizistan'] },
  { city: 'Duşanbe', countryTr: 'Tacikistan', countryEn: 'Tajikistan', aliases: ['dushanbe', 'tacikistan'] },
  { city: 'Tokyo', countryTr: 'Japonya', countryEn: 'Japan', aliases: ['japonya'] },
  { city: 'Osaka', countryTr: 'Japonya', countryEn: 'Japan', aliases: [] },
  { city: 'Kyoto', countryTr: 'Japonya', countryEn: 'Japan', aliases: [] },
  { city: 'Yokohama', countryTr: 'Japonya', countryEn: 'Japan', aliases: [] },
  { city: 'Pekin', countryTr: 'Çin', countryEn: 'China', aliases: ['beijing', 'cin'] },
  { city: 'Şanghay', countryTr: 'Çin', countryEn: 'China', aliases: ['shanghai'] },
  { city: 'Guangzhou', countryTr: 'Çin', countryEn: 'China', aliases: ['kanton'] },
  { city: 'Shenzhen', countryTr: 'Çin', countryEn: 'China', aliases: [] },
  { city: 'Hong Kong', countryTr: 'Hong Kong', countryEn: 'Hong Kong', aliases: ['hk'] },
  { city: 'Taipei', countryTr: 'Tayvan', countryEn: 'Taiwan', aliases: ['tayvan'] },
  { city: 'Seul', countryTr: 'Güney Kore', countryEn: 'South Korea', aliases: ['seoul', 'guney kore', 'korea'] },
  { city: 'Busan', countryTr: 'Güney Kore', countryEn: 'South Korea', aliases: [] },
  { city: 'Singapur', countryTr: 'Singapur', countryEn: 'Singapore', aliases: ['singapore'] },
  { city: 'Bangkok', countryTr: 'Tayland', countryEn: 'Thailand', aliases: ['tayland'] },
  { city: 'Phuket', countryTr: 'Tayland', countryEn: 'Thailand', aliases: [] },
  { city: 'Kuala Lumpur', countryTr: 'Malezya', countryEn: 'Malaysia', aliases: ['kl', 'malezya'] },
  { city: 'Cakarta', countryTr: 'Endonezya', countryEn: 'Indonesia', aliases: ['jakarta', 'endonezya'] },
  { city: 'Bali', countryTr: 'Endonezya', countryEn: 'Indonesia', aliases: ['denpasar'] },
  { city: 'Manila', countryTr: 'Filipinler', countryEn: 'Philippines', aliases: ['filipinler'] },
  { city: 'Hanoi', countryTr: 'Vietnam', countryEn: 'Vietnam', aliases: [] },
  { city: 'Ho Chi Minh', countryTr: 'Vietnam', countryEn: 'Vietnam', aliases: ['saigon'] },
  { city: 'Yeni Delhi', countryTr: 'Hindistan', countryEn: 'India', aliases: ['new delhi', 'delhi', 'hindistan'] },
  { city: 'Mumbai', countryTr: 'Hindistan', countryEn: 'India', aliases: ['bombay'] },
  { city: 'Bangalore', countryTr: 'Hindistan', countryEn: 'India', aliases: ['bengaluru'] },
  { city: 'Kalküta', countryTr: 'Hindistan', countryEn: 'India', aliases: ['kolkata'] },
  { city: 'Haydarabad', countryTr: 'Hindistan', countryEn: 'India', aliases: ['hyderabad'] },
  { city: 'İslamabad', countryTr: 'Pakistan', countryEn: 'Pakistan', aliases: ['islamabad'] },
  { city: 'Karaçi', countryTr: 'Pakistan', countryEn: 'Pakistan', aliases: ['karachi'] },
  { city: 'Lahor', countryTr: 'Pakistan', countryEn: 'Pakistan', aliases: ['lahore'] },
  { city: 'Kabil', countryTr: 'Afganistan', countryEn: 'Afghanistan', aliases: ['kabul', 'afganistan'] },
  { city: 'Tahran', countryTr: 'İran', countryEn: 'Iran', aliases: ['tehran', 'iran'] },
  { city: 'İsfahan', countryTr: 'İran', countryEn: 'Iran', aliases: ['esfahan', 'isfahan'] },
  { city: 'Şiraz', countryTr: 'İran', countryEn: 'Iran', aliases: ['shiraz'] },
  { city: 'Tebriz', countryTr: 'İran', countryEn: 'Iran', aliases: ['tabriz'] },
  { city: 'Bağdat', countryTr: 'Irak', countryEn: 'Iraq', aliases: ['baghdad', 'irak'] },
  { city: 'Erbil', countryTr: 'Irak', countryEn: 'Iraq', aliases: [] },
  { city: 'Basra', countryTr: 'Irak', countryEn: 'Iraq', aliases: [] },
  { city: 'Şam', countryTr: 'Suriye', countryEn: 'Syria', aliases: ['damascus', 'suriye'] },
  { city: 'Halep', countryTr: 'Suriye', countryEn: 'Syria', aliases: ['aleppo'] },
  { city: 'Beyrut', countryTr: 'Lübnan', countryEn: 'Lebanon', aliases: ['beirut', 'lubnan'] },
  { city: 'Amman', countryTr: 'Ürdün', countryEn: 'Jordan', aliases: ['urdun'] },
  { city: 'Kudüs', countryTr: 'Filistin', countryEn: 'Palestine', aliases: ['jerusalem', 'filistin', 'al-quds'] },
  { city: 'Gazze', countryTr: 'Filistin', countryEn: 'Palestine', aliases: ['gaza'] },
  { city: 'Ramallah', countryTr: 'Filistin', countryEn: 'Palestine', aliases: [] },
  { city: 'Tel Aviv', countryTr: 'İsrail', countryEn: 'Israel', aliases: ['israil'] },
  { city: 'Dubai', countryTr: 'Birleşik Arap Emirlikleri', countryEn: 'United Arab Emirates', aliases: ['bae', 'uae'] },
  { city: 'Abu Dabi', countryTr: 'Birleşik Arap Emirlikleri', countryEn: 'United Arab Emirates', aliases: ['abu dhabi'] },
  { city: 'Şarika', countryTr: 'Birleşik Arap Emirlikleri', countryEn: 'United Arab Emirates', aliases: ['sharjah'] },
  { city: 'Doha', countryTr: 'Katar', countryEn: 'Qatar', aliases: ['qatar', 'katar'] },
  { city: 'Riyad', countryTr: 'Suudi Arabistan', countryEn: 'Saudi Arabia', aliases: ['riyadh', 'suudi arabistan'] },
  { city: 'Cidde', countryTr: 'Suudi Arabistan', countryEn: 'Saudi Arabia', aliases: ['jeddah'] },
  { city: 'Mekke', countryTr: 'Suudi Arabistan', countryEn: 'Saudi Arabia', aliases: ['mecca', 'makkah'] },
  { city: 'Medine', countryTr: 'Suudi Arabistan', countryEn: 'Saudi Arabia', aliases: ['medina', 'madinah'] },
  { city: 'Kuveyt', countryTr: 'Kuveyt', countryEn: 'Kuwait', aliases: ['kuwait city', 'kuveyt sehri'] },
  { city: 'Manama', countryTr: 'Bahreyn', countryEn: 'Bahrain', aliases: ['bahreyn'] },
  { city: 'Maskat', countryTr: 'Umman', countryEn: 'Oman', aliases: ['muscat', 'umman'] },
  { city: 'Sana', countryTr: 'Yemen', countryEn: 'Yemen', aliases: ['sanaa', 'yemen'] },

  // Afrika
  { city: 'Kahire', countryTr: 'Mısır', countryEn: 'Egypt', aliases: ['cairo', 'misir'] },
  { city: 'İskenderiye', countryTr: 'Mısır', countryEn: 'Egypt', aliases: ['alexandria'] },
  { city: 'Şarm El-Şeyh', countryTr: 'Mısır', countryEn: 'Egypt', aliases: ['sharm el sheikh'] },
  { city: 'Kazablanka', countryTr: 'Fas', countryEn: 'Morocco', aliases: ['casablanca', 'fas'] },
  { city: 'Marakeş', countryTr: 'Fas', countryEn: 'Morocco', aliases: ['marrakech'] },
  { city: 'Rabat', countryTr: 'Fas', countryEn: 'Morocco', aliases: [] },
  { city: 'Tunus', countryTr: 'Tunus', countryEn: 'Tunisia', aliases: ['tunis'] },
  { city: 'Cezayir', countryTr: 'Cezayir', countryEn: 'Algeria', aliases: ['algiers'] },
  { city: 'Trablus', countryTr: 'Libya', countryEn: 'Libya', aliases: ['tripoli'] },
  { city: 'Hartum', countryTr: 'Sudan', countryEn: 'Sudan', aliases: ['khartoum'] },
  { city: 'Nairobi', countryTr: 'Kenya', countryEn: 'Kenya', aliases: [] },
  { city: 'Mombasa', countryTr: 'Kenya', countryEn: 'Kenya', aliases: [] },
  { city: 'Addis Ababa', countryTr: 'Etiyopya', countryEn: 'Ethiopia', aliases: ['etiyopya'] },
  { city: 'Johannesburg', countryTr: 'Güney Afrika', countryEn: 'South Africa', aliases: ['guney afrika', 'joburg'] },
  { city: 'Cape Town', countryTr: 'Güney Afrika', countryEn: 'South Africa', aliases: ['kaapstad'] },
  { city: 'Pretoria', countryTr: 'Güney Afrika', countryEn: 'South Africa', aliases: [] },
  { city: 'Durban', countryTr: 'Güney Afrika', countryEn: 'South Africa', aliases: [] },
  { city: 'Lagos', countryTr: 'Nijerya', countryEn: 'Nigeria', aliases: ['nijerya'] },
  { city: 'Abuja', countryTr: 'Nijerya', countryEn: 'Nigeria', aliases: [] },
  { city: 'Akra', countryTr: 'Gana', countryEn: 'Ghana', aliases: ['accra', 'gana'] },
  { city: 'Dakar', countryTr: 'Senegal', countryEn: 'Senegal', aliases: [] },
  { city: 'Zanzibar', countryTr: 'Tanzanya', countryEn: 'Tanzania', aliases: ['tanzanya'] },
  { city: 'Darüsselam', countryTr: 'Tanzanya', countryEn: 'Tanzania', aliases: ['dar es salaam'] },

  // Okyanusya
  { city: 'Sidney', countryTr: 'Avustralya', countryEn: 'Australia', aliases: ['sydney', 'avustralya'] },
  { city: 'Melbourne', countryTr: 'Avustralya', countryEn: 'Australia', aliases: [] },
  { city: 'Brisbane', countryTr: 'Avustralya', countryEn: 'Australia', aliases: [] },
  { city: 'Perth', countryTr: 'Avustralya', countryEn: 'Australia', aliases: [] },
  { city: 'Adelaide', countryTr: 'Avustralya', countryEn: 'Australia', aliases: [] },
  { city: 'Auckland', countryTr: 'Yeni Zelanda', countryEn: 'New Zealand', aliases: ['yeni zelanda'] },
  { city: 'Wellington', countryTr: 'Yeni Zelanda', countryEn: 'New Zealand', aliases: [] }
]

const ALL_COUNTRIES = [
  { nameTr: 'Türkiye', nameEn: 'Turkey', code: 'TR', flag: '🇹🇷' },
  { nameTr: 'Almanya', nameEn: 'Germany', code: 'DE', flag: '🇩🇪' },
  { nameTr: 'Amerika Birleşik Devletleri', nameEn: 'United States', code: 'US', flag: '🇺🇸' },
  { nameTr: 'Birleşik Krallık', nameEn: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { nameTr: 'Fransa', nameEn: 'France', code: 'FR', flag: '🇫🇷' },
  { nameTr: 'İtalya', nameEn: 'Italy', code: 'IT', flag: '🇮🇹' },
  { nameTr: 'İspanya', nameEn: 'Spain', code: 'ES', flag: '🇪🇸' },
  { nameTr: 'Hollanda', nameEn: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { nameTr: 'Belçika', nameEn: 'Belgium', code: 'BE', flag: '🇧🇪' },
  { nameTr: 'Avusturya', nameEn: 'Austria', code: 'AT', flag: '🇦🇹' },
  { nameTr: 'İsviçre', nameEn: 'Switzerland', code: 'CH', flag: '🇨🇭' },
  { nameTr: 'İsveç', nameEn: 'Sweden', code: 'SE', flag: '🇸🇪' },
  { nameTr: 'Norveç', nameEn: 'Norway', code: 'NO', flag: '🇳🇴' },
  { nameTr: 'Danimarka', nameEn: 'Denmark', code: 'DK', flag: '🇩🇰' },
  { nameTr: 'Finlandiya', nameEn: 'Finland', code: 'FI', flag: '🇫🇮' },
  { nameTr: 'Polonya', nameEn: 'Poland', code: 'PL', flag: '🇵🇱' },
  { nameTr: 'Portekiz', nameEn: 'Portugal', code: 'PT', flag: '🇵🇹' },
  { nameTr: 'Yunanistan', nameEn: 'Greece', code: 'GR', flag: '🇬🇷' },
  { nameTr: 'Rusya', nameEn: 'Russia', code: 'RU', flag: '🇷🇺' },
  { nameTr: 'Ukrayna', nameEn: 'Ukraine', code: 'UA', flag: '🇺🇦' },
  { nameTr: 'Azerbaycan', nameEn: 'Azerbaijan', code: 'AZ', flag: '🇦🇿' },
  { nameTr: 'Gürcistan', nameEn: 'Georgia', code: 'GE', flag: '🇬🇪' },
  { nameTr: 'Kazakistan', nameEn: 'Kazakhstan', code: 'KZ', flag: '🇰🇿' },
  { nameTr: 'Özbekistan', nameEn: 'Uzbekistan', code: 'UZ', flag: 'UZ' },
  { nameTr: 'Türkmenistan', nameEn: 'Turkmenistan', code: 'TM', flag: '🇹🇲' },
  { nameTr: 'Kırgızistan', nameEn: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬' },
  { nameTr: 'Kuzey Kıbrıs', nameEn: 'Northern Cyprus', code: 'CY', flag: '🇹🇷' },
  { nameTr: 'Kıbrıs', nameEn: 'Cyprus', code: 'CY', flag: '🇨🇾' },
  { nameTr: 'Japonya', nameEn: 'Japan', code: 'JP', flag: '🇯🇵' },
  { nameTr: 'Çin', nameEn: 'China', code: 'CN', flag: '🇨🇳' },
  { nameTr: 'Güney Kore', nameEn: 'South Korea', code: 'KR', flag: '🇰🇷' },
  { nameTr: 'Kanada', nameEn: 'Canada', code: 'CA', flag: '🇨🇦' },
  { nameTr: 'Avustralya', nameEn: 'Australia', code: 'AU', flag: '🇦🇺' },
  { nameTr: 'Yeni Zelanda', nameEn: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { nameTr: 'Brezilya', nameEn: 'Brazil', code: 'BR', flag: '🇧🇷' },
  { nameTr: 'Arjantin', nameEn: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { nameTr: 'Meksika', nameEn: 'Mexico', code: 'MX', flag: '🇲🇽' },
  { nameTr: 'Hindistan', nameEn: 'India', code: 'IN', flag: '🇮🇳' },
  { nameTr: 'Endonezya', nameEn: 'Indonesia', code: 'ID', flag: '🇮🇩' },
  { nameTr: 'Malezya', nameEn: 'Malaysia', code: 'MY', flag: '🇲🇾' },
  { nameTr: 'Singapur', nameEn: 'Singapore', code: 'SG', flag: '🇸🇬' },
  { nameTr: 'Tayland', nameEn: 'Thailand', code: 'TH', flag: '🇹🇭' },
  { nameTr: 'Vietnam', nameEn: 'Vietnam', code: 'VN', flag: '🇻🇳' },
  { nameTr: 'Filipinler', nameEn: 'Philippines', code: 'PH', flag: '🇵🇭' },
  { nameTr: 'Birleşik Arap Emirlikleri', nameEn: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
  { nameTr: 'Katar', nameEn: 'Qatar', code: 'QA', flag: '🇶🇦' },
  { nameTr: 'Suudi Arabistan', nameEn: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
  { nameTr: 'Kuveyt', nameEn: 'Kuwait', code: 'KW', flag: '🇰🇼' },
  { nameTr: 'Bahreyn', nameEn: 'Bahrain', code: 'BH', flag: '🇧🇭' },
  { nameTr: 'Umman', nameEn: 'Oman', code: 'OM', flag: '🇴🇲' },
  { nameTr: 'İran', nameEn: 'Iran', code: 'IR', flag: '🇮🇷' },
  { nameTr: 'Irak', nameEn: 'Iraq', code: 'IQ', flag: '🇮🇶' },
  { nameTr: 'Suriye', nameEn: 'Syria', code: 'SY', flag: '🇸🇾' },
  { nameTr: 'Lübnan', nameEn: 'Lebanon', code: 'LB', flag: '🇱🇧' },
  { nameTr: 'Ürdün', nameEn: 'Jordan', code: 'JO', flag: '🇯🇴' },
  { nameTr: 'Filistin', nameEn: 'Palestine', code: 'PS', flag: '🇵🇸' },
  { nameTr: 'İsrail', nameEn: 'Israel', code: 'IL', flag: '🇮🇱' },
  { nameTr: 'Mısır', nameEn: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { nameTr: 'Fas', nameEn: 'Morocco', code: 'MA', flag: '🇲🇦' },
  { nameTr: 'Tunus', nameEn: 'Tunisia', code: 'TN', flag: '🇹🇳' },
  { nameTr: 'Cezayir', countryTr: 'Cezayir', nameEn: 'Algeria', code: 'DZ', flag: '🇩🇿' },
  { nameTr: 'Libya', nameEn: 'Libya', code: 'LY', flag: '🇱🇾' },
  { nameTr: 'Güney Afrika', nameEn: 'South Africa', code: 'ZA', flag: '🇿🇦' },
  { nameTr: 'Nijerya', nameEn: 'Nigeria', code: 'NG', flag: '🇳🇬' },
  { nameTr: 'Kenya', nameEn: 'Kenya', code: 'KE', flag: '🇰🇪' },
  { nameTr: 'Gana', nameEn: 'Ghana', code: 'GH', flag: '🇬🇭' },
  { nameTr: 'Kolombiya', nameEn: 'Colombia', code: 'CO', flag: '🇨🇴' },
  { nameTr: 'Şili', nameEn: 'Chile', code: 'CL', flag: '🇨🇱' },
  { nameTr: 'Peru', nameEn: 'Peru', code: 'PE', flag: '🇵🇪' },
  { nameTr: 'Venezuela', nameEn: 'Venezuela', code: 'VE', flag: '🇻🇪' },
  { nameTr: 'Çekya', nameEn: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
  { nameTr: 'Macaristan', nameEn: 'Hungary', code: 'HU', flag: '🇭🇺' },
  { nameTr: 'Romanya', nameEn: 'Romania', code: 'RO', flag: '🇷🇴' },
  { nameTr: 'Bulgaristan', nameEn: 'Bulgaria', code: 'BG', flag: '🇧🇬' },
  { nameTr: 'Sırbistan', nameEn: 'Serbia', code: 'RS', flag: '🇷🇸' },
  { nameTr: 'Hırvatistan', nameEn: 'Croatia', code: 'HR', flag: '🇭🇷' },
  { nameTr: 'Bosna-Hersek', nameEn: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦' },
  { nameTr: 'Kuzey Makedonya', nameEn: 'North Macedonia', code: 'MK', flag: 'MK' },
  { nameTr: 'Arnavutluk', nameEn: 'Albania', code: 'AL', flag: '🇦🇱' },
  { nameTr: 'Karadağ', nameEn: 'Montenegro', code: 'ME', flag: '🇲🇪' },
  { nameTr: 'Kosova', nameEn: 'Kosovo', code: 'XK', flag: '🇽🇰' },
  { nameTr: 'İrlanda', nameEn: 'Ireland', code: 'IE', flag: '🇮🇪' },
  { nameTr: 'İzlanda', nameEn: 'Iceland', code: 'IS', flag: '🇮🇸' },
  { nameTr: 'Lüksemburg', nameEn: 'Luxembourg', code: 'LU', flag: '🇱🇺' },
  { nameTr: 'Malta', nameEn: 'Malta', code: 'MT', flag: '🇲🇹' },
  { nameTr: 'Estonya', nameEn: 'Estonia', code: 'EE', flag: '🇪🇪' },
  { nameTr: 'Letonya', nameEn: 'Latvia', code: 'LV', flag: '🇱🇻' },
  { nameTr: 'Litvanya', nameEn: 'Lithuania', code: 'LT', flag: '🇱🇹' },
  { nameTr: 'Slovakya', nameEn: 'Slovakia', code: 'SK', flag: '🇸🇰' },
  { nameTr: 'Slovenya', nameEn: 'Slovenia', code: 'SI', flag: '🇸🇮' },
  { nameTr: 'Belarus', nameEn: 'Belarus', code: 'BY', flag: '🇧🇾' },
  { nameTr: 'Moldova', nameEn: 'Moldova', code: 'MD', flag: '🇲🇩' },
  { nameTr: 'Ermenistan', nameEn: 'Armenia', code: 'AM', flag: '🇦🇲' },
  { nameTr: 'Pakistan', nameEn: 'Pakistan', code: 'PK', flag: '🇵🇰' },
  { nameTr: 'Afganistan', nameEn: 'Afghanistan', code: 'AF', flag: '🇦🇫' },
  { nameTr: 'Bangladeş', nameEn: 'Bangladesh', code: 'BD', flag: '🇧🇩' }
]

function generate() {
  const dataset = []

  // 1. Türkiye İlleri
  TURKEY_PROVINCES.forEach((province) => {
    dataset.push({
      city: province,
      country: 'Türkiye',
      countryEn: 'Turkey',
      code: 'TR',
      state: '',
      kind: 'city',
      flag: '🇹🇷',
      aliases: [province.toLowerCase()]
    })
  })

  // 2. Türkiye İlçeleri
  TURKEY_DISTRICTS.forEach((d) => {
    dataset.push({
      city: `${d.city}, ${d.state}`,
      rawCity: d.city,
      state: d.state,
      country: 'Türkiye',
      countryEn: 'Turkey',
      code: 'TR',
      kind: 'district',
      flag: '🇹🇷',
      aliases: [d.city.toLowerCase(), `${d.city} ${d.state}`.toLowerCase()]
    })
  })

  // 3. Dünya Şehirleri
  WORLD_CITIES.forEach((item) => {
    const matchedCountry = ALL_COUNTRIES.find((c) => c.nameTr === item.countryTr)
    dataset.push({
      city: item.city,
      country: item.countryTr,
      countryEn: item.countryEn,
      code: matchedCountry?.code || '',
      state: '',
      kind: 'city',
      flag: matchedCountry?.flag || '🌍',
      aliases: item.aliases || []
    })
  })

  // 4. Ülkelerin Kendisi
  ALL_COUNTRIES.forEach((c) => {
    dataset.push({
      city: '',
      country: c.nameTr,
      countryEn: c.nameEn,
      code: c.code,
      state: '',
      kind: 'country',
      flag: c.flag,
      aliases: [c.nameTr.toLowerCase(), c.nameEn.toLowerCase(), (c.code || '').toLowerCase()]
    })
  })

  const targetDir = path.join(__dirname, '..', 'src', 'data')
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true })
  }

  const outputPath = path.join(targetDir, 'locationsData.json')
  fs.writeFileSync(outputPath, JSON.stringify(dataset, null, 2), 'utf-8')
  console.log(`Successfully generated ${dataset.length} location entries into ${outputPath}`)
}

generate()
