const express = require('express')
const { authRouter } = require('./auth.routes')
const { adminRouter } = require('./admin.routes')
const { postsRouter } = require('./posts.routes')
const { messagesRouter } = require('./messages.routes')
const { notificationsRouter } = require('./notifications.routes')
const { realtimeRouter } = require('./realtime.routes')
const { reportsRouter } = require('./reports.routes')
const { usersRouter } = require('./users.routes')
const { searchRouter } = require('./search.routes')
const { storiesRouter } = require('./stories.routes')
const { groupsRouter } = require('./groups.routes')
const { performanceRouter } = require('./performance.routes')
const { videoUploadsRouter } = require('./videoUploads.routes')
const { getHealth } = require('../controllers/healthController')

const apiRouter = express.Router()

apiRouter.get('/health', getHealth)
apiRouter.use('/auth', authRouter)
apiRouter.use('/admin', adminRouter)
apiRouter.use('/posts', postsRouter)
apiRouter.use('/messages', messagesRouter)
apiRouter.use('/notifications', notificationsRouter)
apiRouter.use('/realtime', realtimeRouter)
apiRouter.use('/reports', reportsRouter)
apiRouter.use('/users', usersRouter)
apiRouter.use('/search', searchRouter)
apiRouter.use('/stories', storiesRouter)
apiRouter.use('/groups', groupsRouter)
apiRouter.use('/performance', performanceRouter)
apiRouter.use('/video-uploads', videoUploadsRouter)

module.exports = { apiRouter }
